name: User Deployment
run-name: ${{ github.actor }} User Deployment ðŸš€
on: [push, workflow_dispatch]
jobs:
  DEV:
    runs-on: self-hosted
    steps:
      - name: Checkout helm repo
        uses: actions/checkout@v4
        with:
          repository: VenkatBheemireddyOrg/roboshop-helm
      - run: |
          echo $PATH
          bash argocd.sh user dev
        name: Deployment
  QA:
    runs-on: self-hosted
    needs: DEV
    steps:
      - run: echo QA

  UAT:
    runs-on: self-hosted
    needs: QA
    steps:
      - run: echo UAT

  PROD:
    runs-on: self-hosted
    needs: UAT
    steps:
      - run: echo PROD
